### PR TITLE
Create Sum_of_medians.py

### PR DESCRIPTION
**Pull request by lawlesx**
A problem from codeforces
https://codeforces.com/contest/1440/problem/B

### CODE REVIEW

**Comment by lawlesx** [comment]
# Buy the String

### Problem from codeforces https://codeforces.com/contest/1440/problem/A

**Review by piyushgoyal1620 — CHANGES_REQUESTED** [review]
instead of go inside the Python... go inside SRC and then python and then Programs and then add your .py file... and write some good description to this file so it will understandable and make an another PR... then I'll merge it...   but due to less time i'll merge your PR... but make sure You will make these changes ASAP...

**Review by piyushgoyal1620 — CHANGES_REQUESTED** [review]
instead of go inside the Python... go inside SRC and then python and then Programs and then add your .py file... and write some good description to this file so it will understandable and make an another PR... then I'll merge it...   but due to less time i'll merge your PR... but make sure You will make these changes ASAP...

**Comment by lawlesx** [comment]
Will do the changes

**Comment by lawlesx** [comment]
I think I wrote basic documentation like Time complexity of each program

**Pull request merged**
